Item:
    type: entity
    table: item
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        titulo:
            type: string
            length: 255
            fixed: false
            nullable: true
        link:
            type: string
            length: 255
            fixed: false
            nullable: true
        ad:
            type: string
            length: 255
            fixed: false
            nullable: true
    manyToOne:
        categoria:
            targetEntity: Categoria
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
